language: go

os:
    - linux
    - windows
    - osx

go:
    - tip
    - "1.10"
    - 1.9
    - 1.8
    - 1.7

install:
    - mkdir ./writers/rotate/testdata/
    - go get github.com/issue9/assert
    - go get github.com/issue9/term/colors
